string = input()
countA = string.count('a')
countO = string.count('o')
countU = string.count('u')
countI = string.count('i')
countE = string.count('e')
countY = string.count('y')
print('a ' + str(countA) + ',', 'o ' + str(countO) + ',', 'u ' + str(countU) + ',', end=' ')
print('i ' + str(countI) + ',', 'e ' + str(countE) + ',', 'y ' + str(countY) + ',')
